---
title: "Importing STAR templates"
output:
  html_vignette:
    mathjax: null
vignette: >
  %\VignetteIndexEntry{Importing STAR templates}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  collapse=TRUE,
  comment="#>",
  eval=FALSE
)
```

Load package and specify directories:

```{r}
library(gfcmSTAR)
uploads <- "~/StockAssessmentResults/uploads/2021"
star.dir <- file.path(uploads, "WGSAD_Western_Mediterranean")
prop.file <- file.path(uploads, "properties/WGSAD_Western_Mediterranean.xlsx")
```

Read SharePoint properties:

```{r}
prop <- read.properties(prop.file)
```

Import STAR templates:

```{r}
cluster <- import.many.templates(star.dir, prop=prop)
cluster <- import.many.templates(star.dir, prop=prop, qc=TRUE)
cbind(sapply(cluster, class))
errors <- sapply(cluster, class)
cbind(errors[errors=="try-error"])
```

Exclude STAR templates that have errors:

```{r}
cluster.ok <- cluster[sapply(cluster, class) != "try-error"]
cbind(sapply(cluster.ok, class))
```

Check that the `Assessment_ID` fields are unique:

```{r}
id <- peek(cluster.ok, "Assessment_ID")
cbind(id)
if(any(duplicated(id)))
  if[duplicated(id)]
```
